### ISSUE TITLE
ArgumentCountError on AddSegment method

### ISSUE THREAD

**Issue by cephee** [inspector-apm/inspector-laravel#30]
**Describe the bug**
After creating an account and an application and following the installation documentation, I try to run the test command, which returns the error below.

**To Reproduce**
1. After installation 
2. Run `php artisan inspector:test` 

**Screenshots**
<img width="1731" alt="Screenshot 2022-05-20 at 16 20 51" src="https://user-images.githubusercontent.com/6703591/169548387-3485d54a-aa74-462e-80bf-c206f8c583b4.png">

**Web (please complete the following information):**
 - Package Version: 4.7.22
- Laravel framework version: 8.9
- PHP version: 8.0.19 
- Queue: sync (locally)

**Comment by ilvalerione** [comment]
Hi @cephee what is version of PHP installed in your system?

**Comment by cephee** [comment]
> Hi @cephee what is version of PHP installed in your system?

Hey @ilvalerione my local (docker) version is PHP 8.0.19

**Comment by ilvalerione** [comment]
Laravel 8.9 does not exists. I'm trying with the latest 8.x (8.83.13) and PHP 8.019 but the error does not appear. 

Have you also added the ingestion key into the .env file? Or any other thing that can help me reproduce the issue.

**Comment by cephee** [comment]
Yes, sorry my Laravel version "8.83.13" and yes I added the ingestion key :/. And not really no, I debugged the lib with xdebug but I can't find the problem and my middleware is well defined in my kernel

**Comment by ilvalerione** [comment]
Is it continuing to happen?

**Comment by cephee** [comment]
Yes even after reinstalling everything

**Comment by ilvalerione** [comment]
Fixed in the latest version.

**Comment by cephee** [comment]
Still the same error with version 24, but thanks for looking.
